<#
    Full build chain, in the only order that produces a shippable injector.

    The injector does not load enhance.dll from disk -- it carries the DLL as a
    byte array in injector/bytes.hpp and drops it to %TEMP% at runtime. A plain
    solution build links the injector against whatever bytes.hpp happened to be
    on disk and only then relinks the DLL, so the shipped injector is always one
    revision behind. Building through this script instead keeps the payload in
    step with the sources.

    Usage:   powershell -ExecutionPolicy Bypass -File tools\build.ps1
#>

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot

function Find-First([string[]]$paths) {
    foreach ($p in $paths) { if ($p -and (Test-Path $p)) { return $p } }
    return $null
}

# MSBuild: the pinned BuildTools path first, then whatever vswhere reports, then
# any Visual Studio install root. The machine this was pinned to is not the only
# one that builds this.
$msbuild = Find-First @(
    "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
)
if (-not $msbuild) {
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    if (Test-Path $vswhere) {
        $msbuild = & $vswhere -latest -prerelease -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -First 1
    }
}
if (-not $msbuild) {
    $msbuild = Get-ChildItem "C:\Program Files*\Microsoft Visual Studio\*\*\MSBuild\Current\Bin\MSBuild.exe" -ErrorAction SilentlyContinue |
        Select-Object -First 1 -ExpandProperty FullName
}

# Platform toolset. The project pins v143 (Visual Studio 2022). A newer Visual
# Studio does not ship v143 -- it has its own default toolset (VS 18 uses v145)
# -- so ask THIS MSBuild what its default is and build with that, on the command
# line, leaving the checked-in vcxproj on v143 for the machine it was pinned to.
# On the pinned machine the default already is v143, so nothing changes there.
$toolset = "v143"
if ($msbuild) {
    try {
        $probe = & $msbuild (Join-Path $root "enhance.vcxproj") -nologo -p:Configuration=Release -p:Platform=x64 "-getProperty:DefaultPlatformToolset" 2>$null
        $probe = ($probe | Where-Object { $_ -match '^\s*v\d+\s*$' } | Select-Object -Last 1)
        if ($probe) { $toolset = $probe.Trim() }
    } catch {}
}

# javac: pinned JDK first, else the newest jdk-21* under the standard Java dir,
# else the 'latest' junction.
$javac = Find-First @("C:\Program Files\Java\jdk-21.0.11\bin\javac.exe")
if (-not $javac) {
    $jdk = Get-ChildItem "C:\Program Files\Java" -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like 'jdk-21*' -and (Test-Path (Join-Path $_.FullName 'bin\javac.exe')) } |
        Sort-Object Name -Descending | Select-Object -First 1
    if ($jdk) { $javac = Join-Path $jdk.FullName 'bin\javac.exe' }
}
if (-not $javac) { $javac = Find-First @("C:\Program Files\Java\latest\bin\javac.exe") }

# JDK home (…\jdk-XX\bin\javac.exe -> …\jdk-XX). Handed to the DLL build as
# /p:JdkHome so jni.h and jvm.lib resolve against whatever JDK is actually
# installed, not the exact patch level the vcxproj was pinned to.
$jdkHome = if ($javac) { Split-Path (Split-Path $javac) } else { $null }

# python is only needed for the optional mapping check now -- the byte embedding
# is done natively below. The WindowsApps 'python' is a store stub that is worse
# than nothing, so candidates are filtered by actually running them.
function Find-Python {
    $cands = @("python")
    Get-ChildItem "$env:LOCALAPPDATA\Programs\Python" -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { $cands += (Join-Path $_.FullName 'python.exe') }
    $cands += "C:\Users\caves\Documents\catlean\tools-win\python\python.exe"
    foreach ($c in $cands) {
        try {
            $v = & $c --version 2>$null
            if ($LASTEXITCODE -eq 0 -and $v -match 'Python 3') { return $c }
        } catch {}
    }
    return $null
}
$python = Find-Python

# Emit a binary file as a C++ byte-array header. A native port of
# tools/embed_bytes.py so a build no longer hard-depends on a Python
# interpreter; the output format is byte-for-byte identical.
function Embed-Bytes([string]$src, [string]$dst, [string]$symbol, [string]$sizeSymbol) {
    if (-not $sizeSymbol) { $sizeSymbol = "${symbol}_size" }
    $data = [System.IO.File]::ReadAllBytes($src)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("#pragma once`n")
    [void]$sb.Append("#include <cstddef>`n")
    [void]$sb.Append("`n")
    [void]$sb.Append("// Generated by tools/embed_bytes.py -- do not edit by hand.`n")
    [void]$sb.Append("const unsigned char $symbol[] = {`n")
    for ($i = 0; $i -lt $data.Length; $i += 12) {
        $end = [Math]::Min($i + 12, $data.Length)
        $parts = @()
        for ($j = $i; $j -lt $end; $j++) { $parts += ("0x{0:x2}" -f $data[$j]) }
        [void]$sb.Append("`t" + ($parts -join ", "))
        if ($i + 12 -lt $data.Length) { [void]$sb.Append(",`n") } else { [void]$sb.Append("`n") }
    }
    [void]$sb.Append("};`n`nconst size_t $sizeSymbol = sizeof($symbol);`n")
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($dst, $sb.ToString(), $enc)
    return $data.Length
}

$dll = Join-Path $root "x64\Release\enhance.dll"
$injector = Join-Path $root "x64\Release\injector.exe"

function Step($n, $text) {
    Write-Host ""
    Write-Host "[$n/5] $text" -ForegroundColor Cyan
}

function Fail($text) {
    Write-Host "FAILED: $text" -ForegroundColor Red
    exit 1
}

if (-not $msbuild) { Fail "MSBuild not found (looked for VS 2022 BuildTools and any VS via vswhere)" }
if (-not $javac)   { Fail "javac not found (looked for jdk-21 under C:\Program Files\Java)" }
Write-Host "MSBuild: $msbuild"
Write-Host "toolset: $toolset"
Write-Host "javac:   $javac"
if ($python) { Write-Host "python:  $python" } else { Write-Host "python:  none -- mapping check will be skipped" -ForegroundColor Yellow }

# --- 0. Mapping sanity -----------------------------------------------------
# A wrong name compiles perfectly and then resolves to a null id at runtime, so
# the feature just quietly stops working. The checker proves every symbol against
# the published artifacts for all 24 supported versions -- owner and descriptor,
# not just "the name exists somewhere" -- and proves the 1.21.11 column still
# reproduces the header the client was pinned to.
#
# Exit codes: 0 clean, 1 a symbol is wrong (fatal), 3 artifacts unavailable
# (offline, cache cold) which is a warning rather than a broken table.
Step 0 "Verifying mappings across every supported version"

if ($python) {
    & $python (Join-Path $root "tools\verify_mappings.py")
    $verify = $LASTEXITCODE
    if ($verify -eq 1) {
        Fail "mapping verification -- see the list above. A wrong symbol does nothing at runtime and says nothing about it, which is why this stops the build."
    } elseif ($verify -eq 3) {
        Write-Host "WARNING: some versions could not be checked (offline?); tables were not proven this build." -ForegroundColor Yellow
    } elseif ($verify -ne 0) {
        Fail "mapping verification exited with $verify"
    }
} else {
    Write-Host "SKIPPED: no Python interpreter found; mappings are not verified this build." -ForegroundColor Yellow
}

# --- 1. Java renderer -> embedded bytecode --------------------------------
Step 1 "Compiling the Java renderer"

$classOut = Join-Path $env:TEMP "enhance_java_build"
if (Test-Path $classOut) { Remove-Item -Recurse -Force $classOut }
New-Item -ItemType Directory -Force $classOut | Out-Null

$lwjgl = @(
    (Join-Path $root "tools\lib\lwjgl-3.2.2.jar"),
    (Join-Path $root "tools\lib\lwjgl-opengl-3.2.2.jar")
) -join ";"

# --release 17, not 21: the class file is defined into the game's own JVM, and
# 1.20 through 1.20.4 ship Java 17. A class file built for 21 throws
# UnsupportedClassVersionError there, which reads as "the in-world renderer does
# nothing" rather than as a version error. 17 loads on every JVM in the range,
# including 26.x's Java 25.
& $javac --release 17 -Xlint:all -cp $lwjgl -d $classOut (Join-Path $root "enhance\java\EnhanceRenderer.java")
if ($LASTEXITCODE -ne 0) { Fail "javac" }

$classFile = Join-Path $classOut "enhance\EnhanceRenderer.class"
if (-not (Test-Path $classFile)) { Fail "EnhanceRenderer.class was not produced" }

Embed-Bytes $classFile (Join-Path $root "enhance\java\enhance_renderer_class.hpp") "enhance_renderer_class" $null | Out-Null

# --- 2. Client DLL ---------------------------------------------------------
Step 2 "Building enhance.dll"

& $msbuild (Join-Path $root "enhance.vcxproj") /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=$toolset "/p:JdkHome=$jdkHome" /t:Build /m /v:minimal /nologo
if ($LASTEXITCODE -ne 0) { Fail "building enhance.dll" }
if (-not (Test-Path $dll)) { Fail "enhance.dll was not produced" }

# --- 3. DLL -> injector payload -------------------------------------------
Step 3 "Embedding the DLL into the injector payload"

Embed-Bytes $dll (Join-Path $root "injector\bytes.hpp") "dll_bytes" "dll_size" | Out-Null

# --- 4. Injector -----------------------------------------------------------
Step 4 "Building injector.exe"

# OutDir is forced because a direct project build otherwise lands in
# injector\x64\Release while a solution build lands in x64\Release, leaving two
# copies and no way to tell which one is current.
& $msbuild (Join-Path $root "injector\injector.vcxproj") /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=$toolset /p:OutDir="$root\x64\Release\" /t:Rebuild /m /v:minimal /nologo
if ($LASTEXITCODE -ne 0) { Fail "building injector.exe" }

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Get-Item $dll, $injector | Select-Object Name, Length, LastWriteTime | Format-Table -AutoSize

$dllTime = (Get-Item $dll).LastWriteTime
$injTime = (Get-Item $injector).LastWriteTime
if ($injTime -lt $dllTime) {
    Write-Host "WARNING: injector.exe is older than enhance.dll -- the payload is stale." -ForegroundColor Yellow
    exit 1
}
