"""Emit a binary file as a C++ byte-array header.

Used for both payloads this project embeds rather than ships on disk:
the compiled EnhanceRenderer class, and the client DLL carried inside the
injector. Keeping one generator means the two never drift apart in format.

    python tools/embed_bytes.py <input> <output.hpp> <symbol> [size_symbol]

size_symbol defaults to "<symbol>_size". The injector predates this script and
already refers to `dll_size` rather than `dll_bytes_size`, so it passes its own.
"""

import sys


def emit(src_path: str, dst_path: str, symbol: str, size_symbol: str) -> int:
    with open(src_path, "rb") as f:
        data = f.read()

    out = [
        "#pragma once\n",
        "#include <cstddef>\n",
        "\n",
        "// Generated by tools/embed_bytes.py — do not edit by hand.\n",
        "const unsigned char %s[] = {\n" % symbol,
    ]

    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        out.append("\t" + ", ".join("0x%02x" % b for b in chunk))
        out.append(",\n" if i + 12 < len(data) else "\n")

    out.append("};\n\nconst size_t %s = sizeof(%s);\n" % (size_symbol, symbol))

    with open(dst_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))

    return len(data)


def main() -> int:
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        return 2

    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    size_symbol = sys.argv[4] if len(sys.argv) == 5 else symbol + "_size"
    size = emit(src, dst, symbol, size_symbol)
    print("%s -> %s (%d bytes as %s)" % (src, dst, size, symbol))
    return 0


if __name__ == "__main__":
    sys.exit(main())
